more flexible architecture, more price feeds

diff --git a/bin/keeper-config b/bin/keeper-config
--- a/bin/keeper-config
+++ b/bin/keeper-config
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 set -eu
-fail() { echo >&2 ${0##*/}: $*; exit 1; }
-
-conf=~/.keeper.json path=`printf " -e %q" "$@"`
-json-get() { eval jshon -Q <$conf $path $*; }
-
-json-get -u || json-get ||
-fail "error: not found: \``printf .%s "$@"`' (in \`$conf')"
+json_path=$(printf " -e %q" "$@")
+json-get() { eval jshon -Q <<<"$KEEPER_JSON" $json_path $*; }
+json-get -u || json-get || {
+  echo >&2 "${0##*/}: error: not found: \``printf .%s "$@"`'"
+  exit 1
+}
diff --git a/bin/keeper-typecast b/bin/keeper-typecast
--- a/bin/keeper-typecast
+++ b/bin/keeper-typecast
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-set -eu
-fail() { echo >&2 ${0##*/}: $*; exit 1; }
+set -eux
+fail() { echo >&2 "${0##*/}: error: $*"; exit 1; }
 
 case $1 in
 ufixed*x*)
-  keeper typecast-ufixed ${1//[a-z]/ } $2;;
+  keeper typecast-ufixed ${1//[a-z]/ } "$2";;
 *)
-  fail error: unknown type: $1;;
+  fail "unknown type: $1";;
 esac
diff --git a/bin/keeper-typecast-ufixed b/bin/keeper-typecast-ufixed
--- a/bin/keeper-typecast-ufixed
+++ b/bin/keeper-typecast-ufixed
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 set -eu
-fail() { echo >&2 $*; exit 1; }
+fail() { echo >&2 "${0##*/}: error: $*"; exit 1; }
 
-[[ $# = 3 ]] || fail "Usage: ${0##*/} <a> <b> <number>"
+[[ $# = 3 ]] || { echo "Usage: ${0##*/} <a> <b> <number>"; exit 1; }
 a=$1 b=$2 number=$3
 
 hex_char_count=$(((a + b) / 4))
-(( a % 4 == 0 && b % 4 == 0)) ||
-fail "${0##*/}: error: size must be divisible by 4: $a + $b"
+((a % 8 == 0 && b % 8 == 0)) ||
+fail "both parts must be divisible by 8: ${a}x${b}"
 
 echo "obase = 16; scale = 0; ($number * 2 ^ $b) / 1" | bc |
-printf "0x%${hex_char_count}s\n" "`cat`" | tr ' ' 0
+printf "0x%${hex_char_count}s\n" "$(cat)" | tr ' ' 0
